name: y2y
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  path: ^1.9.0
  provider: ^6.1.2
  flutter_screenutil: ^5.9.3
  flutter_launcher_icons: ^0.14.3
  smooth_page_indicator: ^1.2.1
  dio: ^5.8.0+1
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/img/ytylogo.png"
  min_sdk_android: 21 # الحد الأدنى لنسخة أندرويد
  adaptive_icon_background: "#6497d6" # لون الخلفية للأيقونة التكيفية
  adaptive_icon_foreground: "assets/img/ytylogo.png" # الصورة الأمامية للأندرويد

flutter:
  uses-material-design: true

  assets:
    - assets/img/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf

    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf

    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf

    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf

    - family: RalewayDots
      fonts:
        - asset: assets/fonts/RalewayDots-Regular.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf
